// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: course_providers.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getCourseByProviderExternalID = `-- name: GetCourseByProviderExternalID :one
SELECT c.id, c.name, c.street, c.city, c.state, c.zip_code, c.phone, c.cost,
       c.country, c.latitude, c.longitude, c.timezone
FROM course_providers cp
JOIN courses c ON c.id = cp.course_id
WHERE cp.provider = $1 AND cp.external_id = $2
`

type GetCourseByProviderExternalIDParams struct {
	Provider   string
	ExternalID string
}

type GetCourseByProviderExternalIDRow struct {
	ID        int64
	Name      sql.NullString
	Street    sql.NullString
	City      sql.NullString
	State     sql.NullString
	ZipCode   sql.NullString
	Phone     sql.NullString
	Cost      sql.NullString
	Country   sql.NullString
	Latitude  sql.NullFloat64
	Longitude sql.NullFloat64
	Timezone  sql.NullString
}

func (q *Queries) GetCourseByProviderExternalID(ctx context.Context, arg GetCourseByProviderExternalIDParams) (GetCourseByProviderExternalIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCourseByProviderExternalID, arg.Provider, arg.ExternalID)
	var i GetCourseByProviderExternalIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Street,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.Phone,
		&i.Cost,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
		&i.Timezone,
	)
	return i, err
}

const upsertCourseProvider = `-- name: UpsertCourseProvider :one
INSERT INTO course_providers (course_id, provider, external_id, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
ON CONFLICT (provider, external_id) DO UPDATE
SET course_id = EXCLUDED.course_id,
    updated_at = NOW()
RETURNING id, course_id, provider, external_id
`

type UpsertCourseProviderParams struct {
	CourseID   int64
	Provider   string
	ExternalID string
}

type UpsertCourseProviderRow struct {
	ID         int64
	CourseID   int64
	Provider   string
	ExternalID string
}

func (q *Queries) UpsertCourseProvider(ctx context.Context, arg UpsertCourseProviderParams) (UpsertCourseProviderRow, error) {
	row := q.db.QueryRowContext(ctx, upsertCourseProvider, arg.CourseID, arg.Provider, arg.ExternalID)
	var i UpsertCourseProviderRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Provider,
		&i.ExternalID,
	)
	return i, err
}
