// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: course_providers.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getCourseByProviderExternalID = `-- name: GetCourseByProviderExternalID :one
SELECT c.id, c.name, c.street, c.city, c.state, c.zip_code, c.phone, c.cost,
       c.country, c.latitude, c.longitude, c.timezone
FROM course_providers cp
JOIN courses c ON c.id = cp.course_id
WHERE cp.provider = $1 AND cp.external_id = $2
`

type GetCourseByProviderExternalIDParams struct {
	Provider   string
	ExternalID string
}

type GetCourseByProviderExternalIDRow struct {
	ID        int64
	Name      sql.NullString
	Street    sql.NullString
	City      sql.NullString
	State     sql.NullString
	ZipCode   sql.NullString
	Phone     sql.NullString
	Cost      sql.NullString
	Country   sql.NullString
	Latitude  sql.NullFloat64
	Longitude sql.NullFloat64
	Timezone  sql.NullString
}

func (q *Queries) GetCourseByProviderExternalID(ctx context.Context, arg GetCourseByProviderExternalIDParams) (GetCourseByProviderExternalIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCourseByProviderExternalID, arg.Provider, arg.ExternalID)
	var i GetCourseByProviderExternalIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Street,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.Phone,
		&i.Cost,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
		&i.Timezone,
	)
	return i, err
}

const getCourseProvider = `-- name: GetCourseProvider :one
SELECT id, course_id, provider, external_id
FROM course_providers
WHERE provider = $1 AND external_id = $2
`

type GetCourseProviderParams struct {
	Provider   string
	ExternalID string
}

type GetCourseProviderRow struct {
	ID         int64
	CourseID   int64
	Provider   string
	ExternalID string
}

func (q *Queries) GetCourseProvider(ctx context.Context, arg GetCourseProviderParams) (GetCourseProviderRow, error) {
	row := q.db.QueryRowContext(ctx, getCourseProvider, arg.Provider, arg.ExternalID)
	var i GetCourseProviderRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Provider,
		&i.ExternalID,
	)
	return i, err
}

const getCourseProviderByCourseAndProvider = `-- name: GetCourseProviderByCourseAndProvider :one
SELECT id, course_id, provider, external_id
FROM course_providers
WHERE course_id = $1 AND provider = $2
`

type GetCourseProviderByCourseAndProviderParams struct {
	CourseID int64
	Provider string
}

type GetCourseProviderByCourseAndProviderRow struct {
	ID         int64
	CourseID   int64
	Provider   string
	ExternalID string
}

func (q *Queries) GetCourseProviderByCourseAndProvider(ctx context.Context, arg GetCourseProviderByCourseAndProviderParams) (GetCourseProviderByCourseAndProviderRow, error) {
	row := q.db.QueryRowContext(ctx, getCourseProviderByCourseAndProvider, arg.CourseID, arg.Provider)
	var i GetCourseProviderByCourseAndProviderRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Provider,
		&i.ExternalID,
	)
	return i, err
}

const insertCourseProvider = `-- name: InsertCourseProvider :one
INSERT INTO course_providers (course_id, provider, external_id, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
RETURNING id, course_id, provider, external_id
`

type InsertCourseProviderParams struct {
	CourseID   int64
	Provider   string
	ExternalID string
}

type InsertCourseProviderRow struct {
	ID         int64
	CourseID   int64
	Provider   string
	ExternalID string
}

func (q *Queries) InsertCourseProvider(ctx context.Context, arg InsertCourseProviderParams) (InsertCourseProviderRow, error) {
	row := q.db.QueryRowContext(ctx, insertCourseProvider, arg.CourseID, arg.Provider, arg.ExternalID)
	var i InsertCourseProviderRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Provider,
		&i.ExternalID,
	)
	return i, err
}
