// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (name, street, city, state, zip_code, phone, cost, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), NOW())
RETURNING id, name, street, city, state, zip_code, phone, cost
`

type CreateCourseParams struct {
	Name    sql.NullString
	Street  sql.NullString
	City    sql.NullString
	State   sql.NullString
	ZipCode sql.NullString
	Phone   sql.NullString
	Cost    sql.NullString
}

type CreateCourseRow struct {
	ID      int64
	Name    sql.NullString
	Street  sql.NullString
	City    sql.NullString
	State   sql.NullString
	ZipCode sql.NullString
	Phone   sql.NullString
	Cost    sql.NullString
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (CreateCourseRow, error) {
	row := q.db.QueryRowContext(ctx, createCourse,
		arg.Name,
		arg.Street,
		arg.City,
		arg.State,
		arg.ZipCode,
		arg.Phone,
		arg.Cost,
	)
	var i CreateCourseRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Street,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.Phone,
		&i.Cost,
	)
	return i, err
}

const getCourseByNameAndCity = `-- name: GetCourseByNameAndCity :one
SELECT id, name, street, city, state, zip_code, phone, cost
FROM courses
WHERE name = $1 AND city = $2
`

type GetCourseByNameAndCityParams struct {
	Name sql.NullString
	City sql.NullString
}

type GetCourseByNameAndCityRow struct {
	ID      int64
	Name    sql.NullString
	Street  sql.NullString
	City    sql.NullString
	State   sql.NullString
	ZipCode sql.NullString
	Phone   sql.NullString
	Cost    sql.NullString
}

func (q *Queries) GetCourseByNameAndCity(ctx context.Context, arg GetCourseByNameAndCityParams) (GetCourseByNameAndCityRow, error) {
	row := q.db.QueryRowContext(ctx, getCourseByNameAndCity, arg.Name, arg.City)
	var i GetCourseByNameAndCityRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Street,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.Phone,
		&i.Cost,
	)
	return i, err
}

const listCourses = `-- name: ListCourses :many
SELECT id, name, street, city, state, zip_code, phone, cost
FROM courses
ORDER BY id
`

type ListCoursesRow struct {
	ID      int64
	Name    sql.NullString
	Street  sql.NullString
	City    sql.NullString
	State   sql.NullString
	ZipCode sql.NullString
	Phone   sql.NullString
	Cost    sql.NullString
}

func (q *Queries) ListCourses(ctx context.Context) ([]ListCoursesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCoursesRow
	for rows.Next() {
		var i ListCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Street,
			&i.City,
			&i.State,
			&i.ZipCode,
			&i.Phone,
			&i.Cost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
