// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: friendships.sql

package sqlcgen

import (
	"context"
)

const createFriendship = `-- name: CreateFriendship :one
INSERT INTO friendships (requester_id, addressee_id, status, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
RETURNING id, requester_id, addressee_id, status
`

type CreateFriendshipParams struct {
	RequesterID int64
	AddresseeID int64
	Status      int32
}

type CreateFriendshipRow struct {
	ID          int64
	RequesterID int64
	AddresseeID int64
	Status      int32
}

func (q *Queries) CreateFriendship(ctx context.Context, arg CreateFriendshipParams) (CreateFriendshipRow, error) {
	row := q.db.QueryRowContext(ctx, createFriendship, arg.RequesterID, arg.AddresseeID, arg.Status)
	var i CreateFriendshipRow
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
	)
	return i, err
}

const deleteFriendshipByID = `-- name: DeleteFriendshipByID :exec
DELETE FROM friendships
WHERE id = $1
`

func (q *Queries) DeleteFriendshipByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFriendshipByID, id)
	return err
}

const findFriendship = `-- name: FindFriendship :one
SELECT id, requester_id, addressee_id, status
FROM friendships
WHERE requester_id = $1 AND addressee_id = $2
`

type FindFriendshipParams struct {
	RequesterID int64
	AddresseeID int64
}

type FindFriendshipRow struct {
	ID          int64
	RequesterID int64
	AddresseeID int64
	Status      int32
}

func (q *Queries) FindFriendship(ctx context.Context, arg FindFriendshipParams) (FindFriendshipRow, error) {
	row := q.db.QueryRowContext(ctx, findFriendship, arg.RequesterID, arg.AddresseeID)
	var i FindFriendshipRow
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
	)
	return i, err
}

const findFriendshipBetween = `-- name: FindFriendshipBetween :one
SELECT id, requester_id, addressee_id, status
FROM friendships
WHERE (requester_id = $1 AND addressee_id = $2)
   OR (requester_id = $2 AND addressee_id = $1)
LIMIT 1
`

type FindFriendshipBetweenParams struct {
	RequesterID int64
	AddresseeID int64
}

type FindFriendshipBetweenRow struct {
	ID          int64
	RequesterID int64
	AddresseeID int64
	Status      int32
}

func (q *Queries) FindFriendshipBetween(ctx context.Context, arg FindFriendshipBetweenParams) (FindFriendshipBetweenRow, error) {
	row := q.db.QueryRowContext(ctx, findFriendshipBetween, arg.RequesterID, arg.AddresseeID)
	var i FindFriendshipBetweenRow
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
	)
	return i, err
}

const getFriendshipByID = `-- name: GetFriendshipByID :one
SELECT id, requester_id, addressee_id, status
FROM friendships
WHERE id = $1
`

type GetFriendshipByIDRow struct {
	ID          int64
	RequesterID int64
	AddresseeID int64
	Status      int32
}

func (q *Queries) GetFriendshipByID(ctx context.Context, id int64) (GetFriendshipByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getFriendshipByID, id)
	var i GetFriendshipByIDRow
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
	)
	return i, err
}

const listAcceptedFriendIDs = `-- name: ListAcceptedFriendIDs :many
SELECT CASE
    WHEN requester_id = $1 THEN addressee_id
    ELSE requester_id
END::bigint AS friend_id
FROM friendships
WHERE status = 1
  AND (requester_id = $1 OR addressee_id = $1)
`

func (q *Queries) ListAcceptedFriendIDs(ctx context.Context, requesterID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listAcceptedFriendIDs, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var friend_id int64
		if err := rows.Scan(&friend_id); err != nil {
			return nil, err
		}
		items = append(items, friend_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomingPendingFriendships = `-- name: ListIncomingPendingFriendships :many
SELECT id, requester_id, addressee_id, status
FROM friendships
WHERE addressee_id = $1 AND status = 0
ORDER BY id DESC
`

type ListIncomingPendingFriendshipsRow struct {
	ID          int64
	RequesterID int64
	AddresseeID int64
	Status      int32
}

func (q *Queries) ListIncomingPendingFriendships(ctx context.Context, addresseeID int64) ([]ListIncomingPendingFriendshipsRow, error) {
	rows, err := q.db.QueryContext(ctx, listIncomingPendingFriendships, addresseeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIncomingPendingFriendshipsRow
	for rows.Next() {
		var i ListIncomingPendingFriendshipsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequesterID,
			&i.AddresseeID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutgoingPendingFriendships = `-- name: ListOutgoingPendingFriendships :many
SELECT id, requester_id, addressee_id, status
FROM friendships
WHERE requester_id = $1 AND status = 0
ORDER BY id DESC
`

type ListOutgoingPendingFriendshipsRow struct {
	ID          int64
	RequesterID int64
	AddresseeID int64
	Status      int32
}

func (q *Queries) ListOutgoingPendingFriendships(ctx context.Context, requesterID int64) ([]ListOutgoingPendingFriendshipsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOutgoingPendingFriendships, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOutgoingPendingFriendshipsRow
	for rows.Next() {
		var i ListOutgoingPendingFriendshipsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequesterID,
			&i.AddresseeID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFriendshipStatus = `-- name: UpdateFriendshipStatus :one
UPDATE friendships
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, requester_id, addressee_id, status
`

type UpdateFriendshipStatusParams struct {
	ID     int64
	Status int32
}

type UpdateFriendshipStatusRow struct {
	ID          int64
	RequesterID int64
	AddresseeID int64
	Status      int32
}

func (q *Queries) UpdateFriendshipStatus(ctx context.Context, arg UpdateFriendshipStatusParams) (UpdateFriendshipStatusRow, error) {
	row := q.db.QueryRowContext(ctx, updateFriendshipStatus, arg.ID, arg.Status)
	var i UpdateFriendshipStatusRow
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
	)
	return i, err
}
