// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const countActiveGroupMembers = `-- name: CountActiveGroupMembers :one
SELECT COUNT(*)::bigint
FROM group_memberships
WHERE group_id = $1
  AND status = 'active'
`

func (q *Queries) CountActiveGroupMembers(ctx context.Context, groupID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveGroupMembers, groupID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups
WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, id)
	return err
}

const deleteGroupMembership = `-- name: DeleteGroupMembership :exec
DELETE FROM group_memberships
WHERE group_id = $1
  AND player_id = $2
`

type DeleteGroupMembershipParams struct {
	GroupID  int64
	PlayerID int64
}

func (q *Queries) DeleteGroupMembership(ctx context.Context, arg DeleteGroupMembershipParams) error {
	_, err := q.db.ExecContext(ctx, deleteGroupMembership, arg.GroupID, arg.PlayerID)
	return err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, owner_player_id, name, description, privacy, created_at, updated_at
FROM groups
WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id int64) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.OwnerPlayerID,
		&i.Name,
		&i.Description,
		&i.Privacy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupInvitationByID = `-- name: GetGroupInvitationByID :one
SELECT id, group_id, inviter_player_id, invitee_player_id, created_at, expires_at, accepted_at, declined_at
FROM group_invitations
WHERE id = $1
`

func (q *Queries) GetGroupInvitationByID(ctx context.Context, id int64) (GroupInvitation, error) {
	row := q.db.QueryRowContext(ctx, getGroupInvitationByID, id)
	var i GroupInvitation
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.InviterPlayerID,
		&i.InviteePlayerID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.DeclinedAt,
	)
	return i, err
}

const getGroupMembership = `-- name: GetGroupMembership :one
SELECT group_id, player_id, role, status, created_at, updated_at
FROM group_memberships
WHERE group_id = $1
  AND player_id = $2
`

type GetGroupMembershipParams struct {
	GroupID  int64
	PlayerID int64
}

func (q *Queries) GetGroupMembership(ctx context.Context, arg GetGroupMembershipParams) (GroupMembership, error) {
	row := q.db.QueryRowContext(ctx, getGroupMembership, arg.GroupID, arg.PlayerID)
	var i GroupMembership
	err := row.Scan(
		&i.GroupID,
		&i.PlayerID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOutstandingGroupInvitation = `-- name: GetOutstandingGroupInvitation :one
SELECT id, group_id, inviter_player_id, invitee_player_id, created_at, expires_at, accepted_at, declined_at
FROM group_invitations
WHERE group_id = $1
  AND invitee_player_id = $2
  AND accepted_at IS NULL
  AND declined_at IS NULL
`

type GetOutstandingGroupInvitationParams struct {
	GroupID         int64
	InviteePlayerID int64
}

func (q *Queries) GetOutstandingGroupInvitation(ctx context.Context, arg GetOutstandingGroupInvitationParams) (GroupInvitation, error) {
	row := q.db.QueryRowContext(ctx, getOutstandingGroupInvitation, arg.GroupID, arg.InviteePlayerID)
	var i GroupInvitation
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.InviterPlayerID,
		&i.InviteePlayerID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.DeclinedAt,
	)
	return i, err
}

const insertGroup = `-- name: InsertGroup :one
INSERT INTO groups (owner_player_id, name, description, privacy, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
RETURNING id, owner_player_id, name, description, privacy, created_at, updated_at
`

type InsertGroupParams struct {
	OwnerPlayerID int64
	Name          string
	Description   string
	Privacy       string
}

func (q *Queries) InsertGroup(ctx context.Context, arg InsertGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, insertGroup,
		arg.OwnerPlayerID,
		arg.Name,
		arg.Description,
		arg.Privacy,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.OwnerPlayerID,
		&i.Name,
		&i.Description,
		&i.Privacy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertGroupInvitation = `-- name: InsertGroupInvitation :one
INSERT INTO group_invitations (
    group_id, inviter_player_id, invitee_player_id, created_at, expires_at
)
VALUES ($1, $2, $3, NOW(), $4)
RETURNING id, group_id, inviter_player_id, invitee_player_id, created_at, expires_at, accepted_at, declined_at
`

type InsertGroupInvitationParams struct {
	GroupID         int64
	InviterPlayerID int64
	InviteePlayerID int64
	ExpiresAt       sql.NullTime
}

func (q *Queries) InsertGroupInvitation(ctx context.Context, arg InsertGroupInvitationParams) (GroupInvitation, error) {
	row := q.db.QueryRowContext(ctx, insertGroupInvitation,
		arg.GroupID,
		arg.InviterPlayerID,
		arg.InviteePlayerID,
		arg.ExpiresAt,
	)
	var i GroupInvitation
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.InviterPlayerID,
		&i.InviteePlayerID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.DeclinedAt,
	)
	return i, err
}

const insertGroupMembership = `-- name: InsertGroupMembership :one
INSERT INTO group_memberships (group_id, player_id, role, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
RETURNING group_id, player_id, role, status, created_at, updated_at
`

type InsertGroupMembershipParams struct {
	GroupID  int64
	PlayerID int64
	Role     string
	Status   string
}

func (q *Queries) InsertGroupMembership(ctx context.Context, arg InsertGroupMembershipParams) (GroupMembership, error) {
	row := q.db.QueryRowContext(ctx, insertGroupMembership,
		arg.GroupID,
		arg.PlayerID,
		arg.Role,
		arg.Status,
	)
	var i GroupMembership
	err := row.Scan(
		&i.GroupID,
		&i.PlayerID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveGroupMembers = `-- name: ListActiveGroupMembers :many
SELECT m.group_id, m.player_id, m.role, m.status, m.created_at, m.updated_at, p.name AS player_name
FROM group_memberships m
INNER JOIN players p ON p.id = m.player_id
WHERE m.group_id = $1
  AND m.status = 'active'
ORDER BY
    CASE m.role WHEN 'owner' THEN 0 WHEN 'admin' THEN 1 ELSE 2 END,
    p.name ASC,
    m.player_id ASC
LIMIT $2 OFFSET $3
`

type ListActiveGroupMembersParams struct {
	GroupID int64
	Limit   int32
	Offset  int32
}

type ListActiveGroupMembersRow struct {
	GroupID    int64
	PlayerID   int64
	Role       string
	Status     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	PlayerName sql.NullString
}

func (q *Queries) ListActiveGroupMembers(ctx context.Context, arg ListActiveGroupMembersParams) ([]ListActiveGroupMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveGroupMembers, arg.GroupID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveGroupMembersRow
	for rows.Next() {
		var i ListActiveGroupMembersRow
		if err := rows.Scan(
			&i.GroupID,
			&i.PlayerID,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PlayerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupInvitationsByInvitee = `-- name: ListGroupInvitationsByInvitee :many
SELECT i.id, i.group_id, i.inviter_player_id, i.invitee_player_id,
       i.created_at, i.expires_at, i.accepted_at, i.declined_at,
       g.name AS group_name, p.name AS inviter_name
FROM group_invitations i
INNER JOIN groups g ON g.id = i.group_id
INNER JOIN players p ON p.id = i.inviter_player_id
WHERE i.invitee_player_id = $1
  AND i.accepted_at IS NULL
  AND i.declined_at IS NULL
ORDER BY i.created_at DESC
`

type ListGroupInvitationsByInviteeRow struct {
	ID              int64
	GroupID         int64
	InviterPlayerID int64
	InviteePlayerID int64
	CreatedAt       time.Time
	ExpiresAt       sql.NullTime
	AcceptedAt      sql.NullTime
	DeclinedAt      sql.NullTime
	GroupName       string
	InviterName     sql.NullString
}

func (q *Queries) ListGroupInvitationsByInvitee(ctx context.Context, inviteePlayerID int64) ([]ListGroupInvitationsByInviteeRow, error) {
	rows, err := q.db.QueryContext(ctx, listGroupInvitationsByInvitee, inviteePlayerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupInvitationsByInviteeRow
	for rows.Next() {
		var i ListGroupInvitationsByInviteeRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.InviterPlayerID,
			&i.InviteePlayerID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.DeclinedAt,
			&i.GroupName,
			&i.InviterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupSummariesByPlayer = `-- name: ListGroupSummariesByPlayer :many
SELECT
    g.id,
    g.owner_player_id,
    g.name,
    g.description,
    g.privacy,
    g.created_at,
    g.updated_at,
    COALESCE(owner.name, '') AS owner_name,
    (
        SELECT COUNT(*)::bigint
        FROM group_memberships cm
        WHERE cm.group_id = g.id
          AND cm.status = 'active'
    ) AS member_count,
    m.role AS viewer_role,
    m.status AS viewer_status,
    m.created_at AS viewer_created_at,
    m.updated_at AS viewer_updated_at
FROM groups g
INNER JOIN group_memberships m ON m.group_id = g.id
INNER JOIN players owner ON owner.id = g.owner_player_id
WHERE m.player_id = $1
  AND m.status = 'active'
ORDER BY g.name ASC, g.id ASC
LIMIT $3 OFFSET $2
`

type ListGroupSummariesByPlayerParams struct {
	PlayerID int64
	Offset   int32
	Limit    int32
}

type ListGroupSummariesByPlayerRow struct {
	ID              int64
	OwnerPlayerID   int64
	Name            string
	Description     string
	Privacy         string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	OwnerName       string
	MemberCount     int64
	ViewerRole      string
	ViewerStatus    string
	ViewerCreatedAt time.Time
	ViewerUpdatedAt time.Time
}

func (q *Queries) ListGroupSummariesByPlayer(ctx context.Context, arg ListGroupSummariesByPlayerParams) ([]ListGroupSummariesByPlayerRow, error) {
	rows, err := q.db.QueryContext(ctx, listGroupSummariesByPlayer, arg.PlayerID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupSummariesByPlayerRow
	for rows.Next() {
		var i ListGroupSummariesByPlayerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerPlayerID,
			&i.Name,
			&i.Description,
			&i.Privacy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
			&i.MemberCount,
			&i.ViewerRole,
			&i.ViewerStatus,
			&i.ViewerCreatedAt,
			&i.ViewerUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsByPlayer = `-- name: ListGroupsByPlayer :many
SELECT g.id, g.owner_player_id, g.name, g.description, g.privacy, g.created_at, g.updated_at
FROM groups g
INNER JOIN group_memberships m ON m.group_id = g.id
WHERE m.player_id = $1
  AND m.status = 'active'
ORDER BY g.name ASC, g.id ASC
LIMIT $2 OFFSET $3
`

type ListGroupsByPlayerParams struct {
	PlayerID int64
	Limit    int32
	Offset   int32
}

func (q *Queries) ListGroupsByPlayer(ctx context.Context, arg ListGroupsByPlayerParams) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroupsByPlayer, arg.PlayerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.OwnerPlayerID,
			&i.Name,
			&i.Description,
			&i.Privacy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutstandingGroupInvitations = `-- name: ListOutstandingGroupInvitations :many
SELECT i.id, i.group_id, i.inviter_player_id, i.invitee_player_id,
       i.created_at, i.expires_at, i.accepted_at, i.declined_at,
       g.name AS group_name, inviter.name AS inviter_name, invitee.name AS invitee_name
FROM group_invitations i
INNER JOIN groups g ON g.id = i.group_id
INNER JOIN players inviter ON inviter.id = i.inviter_player_id
INNER JOIN players invitee ON invitee.id = i.invitee_player_id
WHERE i.group_id = $1
  AND i.accepted_at IS NULL
  AND i.declined_at IS NULL
ORDER BY i.created_at DESC, i.id DESC
`

type ListOutstandingGroupInvitationsRow struct {
	ID              int64
	GroupID         int64
	InviterPlayerID int64
	InviteePlayerID int64
	CreatedAt       time.Time
	ExpiresAt       sql.NullTime
	AcceptedAt      sql.NullTime
	DeclinedAt      sql.NullTime
	GroupName       string
	InviterName     sql.NullString
	InviteeName     sql.NullString
}

func (q *Queries) ListOutstandingGroupInvitations(ctx context.Context, groupID int64) ([]ListOutstandingGroupInvitationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOutstandingGroupInvitations, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOutstandingGroupInvitationsRow
	for rows.Next() {
		var i ListOutstandingGroupInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.InviterPlayerID,
			&i.InviteePlayerID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.DeclinedAt,
			&i.GroupName,
			&i.InviterName,
			&i.InviteeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingGroupMembers = `-- name: ListPendingGroupMembers :many
SELECT m.group_id, m.player_id, m.role, m.status, m.created_at, m.updated_at, p.name AS player_name
FROM group_memberships m
INNER JOIN players p ON p.id = m.player_id
WHERE m.group_id = $1
  AND m.status = 'pending'
ORDER BY m.created_at ASC, m.player_id ASC
`

type ListPendingGroupMembersRow struct {
	GroupID    int64
	PlayerID   int64
	Role       string
	Status     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	PlayerName sql.NullString
}

func (q *Queries) ListPendingGroupMembers(ctx context.Context, groupID int64) ([]ListPendingGroupMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingGroupMembersRow
	for rows.Next() {
		var i ListPendingGroupMembersRow
		if err := rows.Scan(
			&i.GroupID,
			&i.PlayerID,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PlayerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicGroupSummaries = `-- name: ListPublicGroupSummaries :many
SELECT
    g.id,
    g.owner_player_id,
    g.name,
    g.description,
    g.privacy,
    g.created_at,
    g.updated_at,
    COALESCE(owner.name, '') AS owner_name,
    (
        SELECT COUNT(*)::bigint
        FROM group_memberships cm
        WHERE cm.group_id = g.id
          AND cm.status = 'active'
    ) AS member_count,
    viewer.role AS viewer_role,
    viewer.status AS viewer_status,
    viewer.created_at AS viewer_created_at,
    viewer.updated_at AS viewer_updated_at
FROM groups g
INNER JOIN players owner ON owner.id = g.owner_player_id
LEFT JOIN group_memberships viewer
    ON viewer.group_id = g.id
   AND viewer.player_id = $1
WHERE g.privacy = 'public'
  AND ($2::text = '' OR g.name ILIKE '%' || $2::text || '%')
ORDER BY g.name ASC, g.id ASC
LIMIT $4 OFFSET $3
`

type ListPublicGroupSummariesParams struct {
	PlayerID int64
	Search   string
	Offset   int32
	Limit    int32
}

type ListPublicGroupSummariesRow struct {
	ID              int64
	OwnerPlayerID   int64
	Name            string
	Description     string
	Privacy         string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	OwnerName       string
	MemberCount     int64
	ViewerRole      sql.NullString
	ViewerStatus    sql.NullString
	ViewerCreatedAt sql.NullTime
	ViewerUpdatedAt sql.NullTime
}

func (q *Queries) ListPublicGroupSummaries(ctx context.Context, arg ListPublicGroupSummariesParams) ([]ListPublicGroupSummariesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublicGroupSummaries,
		arg.PlayerID,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicGroupSummariesRow
	for rows.Next() {
		var i ListPublicGroupSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerPlayerID,
			&i.Name,
			&i.Description,
			&i.Privacy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
			&i.MemberCount,
			&i.ViewerRole,
			&i.ViewerStatus,
			&i.ViewerCreatedAt,
			&i.ViewerUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicGroups = `-- name: ListPublicGroups :many
SELECT id, owner_player_id, name, description, privacy, created_at, updated_at
FROM groups
WHERE privacy = 'public'
  AND ($1::text = '' OR name ILIKE '%' || $1::text || '%')
ORDER BY name ASC, id ASC
LIMIT $3 OFFSET $2
`

type ListPublicGroupsParams struct {
	Search string
	Offset int32
	Limit  int32
}

func (q *Queries) ListPublicGroups(ctx context.Context, arg ListPublicGroupsParams) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listPublicGroups, arg.Search, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.OwnerPlayerID,
			&i.Name,
			&i.Description,
			&i.Privacy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGroupInvitationAccepted = `-- name: MarkGroupInvitationAccepted :one
UPDATE group_invitations
SET accepted_at = NOW()
WHERE id = $1
  AND accepted_at IS NULL
  AND declined_at IS NULL
RETURNING id, group_id, inviter_player_id, invitee_player_id, created_at, expires_at, accepted_at, declined_at
`

func (q *Queries) MarkGroupInvitationAccepted(ctx context.Context, id int64) (GroupInvitation, error) {
	row := q.db.QueryRowContext(ctx, markGroupInvitationAccepted, id)
	var i GroupInvitation
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.InviterPlayerID,
		&i.InviteePlayerID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.DeclinedAt,
	)
	return i, err
}

const markGroupInvitationDeclined = `-- name: MarkGroupInvitationDeclined :one
UPDATE group_invitations
SET declined_at = NOW()
WHERE id = $1
  AND accepted_at IS NULL
  AND declined_at IS NULL
RETURNING id, group_id, inviter_player_id, invitee_player_id, created_at, expires_at, accepted_at, declined_at
`

func (q *Queries) MarkGroupInvitationDeclined(ctx context.Context, id int64) (GroupInvitation, error) {
	row := q.db.QueryRowContext(ctx, markGroupInvitationDeclined, id)
	var i GroupInvitation
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.InviterPlayerID,
		&i.InviteePlayerID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.DeclinedAt,
	)
	return i, err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups
SET name = $2,
    description = $3,
    privacy = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, owner_player_id, name, description, privacy, created_at, updated_at
`

type UpdateGroupParams struct {
	ID          int64
	Name        string
	Description string
	Privacy     string
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, updateGroup,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Privacy,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.OwnerPlayerID,
		&i.Name,
		&i.Description,
		&i.Privacy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGroupMembership = `-- name: UpdateGroupMembership :one
UPDATE group_memberships
SET role = $3,
    status = $4,
    updated_at = NOW()
WHERE group_id = $1
  AND player_id = $2
RETURNING group_id, player_id, role, status, created_at, updated_at
`

type UpdateGroupMembershipParams struct {
	GroupID  int64
	PlayerID int64
	Role     string
	Status   string
}

func (q *Queries) UpdateGroupMembership(ctx context.Context, arg UpdateGroupMembershipParams) (GroupMembership, error) {
	row := q.db.QueryRowContext(ctx, updateGroupMembership,
		arg.GroupID,
		arg.PlayerID,
		arg.Role,
		arg.Status,
	)
	var i GroupMembership
	err := row.Scan(
		&i.GroupID,
		&i.PlayerID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGroupOwner = `-- name: UpdateGroupOwner :exec
UPDATE groups
SET owner_player_id = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateGroupOwnerParams struct {
	ID            int64
	OwnerPlayerID int64
}

func (q *Queries) UpdateGroupOwner(ctx context.Context, arg UpdateGroupOwnerParams) error {
	_, err := q.db.ExecContext(ctx, updateGroupOwner, arg.ID, arg.OwnerPlayerID)
	return err
}
