// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"time"
)

type Course struct {
	ID        int64
	Name      sql.NullString
	Street    sql.NullString
	City      sql.NullString
	State     sql.NullString
	ZipCode   sql.NullString
	Phone     sql.NullString
	Cost      sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Event struct {
	ID            int64
	CourseID      sql.NullInt32
	Date          sql.NullString
	TeeTime       sql.NullString
	OpenSpots     sql.NullInt32
	NumberOfHoles sql.NullString
	Private       sql.NullBool
	HostID        sql.NullInt32
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Friendship struct {
	ID          int64
	RequesterID sql.NullInt32
	AddresseeID sql.NullInt32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Status      int32
}

type Player struct {
	ID             int64
	Name           sql.NullString
	Phone          sql.NullString
	Email          sql.NullString
	Username       sql.NullString
	PasswordDigest sql.NullString
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type PlayerEvent struct {
	ID           int64
	PlayerID     sql.NullInt64
	EventID      sql.NullInt64
	InviteStatus sql.NullInt32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Post struct {
	ID        int64
	PlayerID  int64
	Body      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Reaction struct {
	ID        int64
	PostID    int64
	PlayerID  int64
	Emoji     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Reply struct {
	ID        int64
	PostID    int64
	PlayerID  int64
	Body      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
