// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"time"
)

type Course struct {
	ID        int64
	Name      sql.NullString
	Street    sql.NullString
	City      sql.NullString
	State     sql.NullString
	ZipCode   sql.NullString
	Phone     sql.NullString
	Cost      sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	Country   sql.NullString
	Latitude  sql.NullFloat64
	Longitude sql.NullFloat64
	Timezone  sql.NullString
}

type CourseProvider struct {
	ID         int64
	CourseID   int64
	Provider   string
	ExternalID string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Event struct {
	ID            int64
	CourseID      int64
	OpenSpots     sql.NullInt32
	NumberOfHoles sql.NullString
	Private       sql.NullBool
	HostID        int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	StartsAt      time.Time
	TeeTimeID     sql.NullInt64
}

type Friendship struct {
	ID          int64
	RequesterID int64
	AddresseeID int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Status      int32
}

type Player struct {
	ID             int64
	Name           sql.NullString
	Phone          sql.NullString
	Email          sql.NullString
	Username       sql.NullString
	PasswordDigest sql.NullString
	CreatedAt      time.Time
	UpdatedAt      time.Time
	TokenVersion   int32
}

type PlayerEvent struct {
	ID           int64
	PlayerID     int64
	EventID      int64
	InviteStatus int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Post struct {
	ID        int64
	PlayerID  int64
	Body      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Reaction struct {
	ID        int64
	PostID    int64
	PlayerID  int64
	Emoji     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Reply struct {
	ID        int64
	PostID    int64
	PlayerID  int64
	Body      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TeeTime struct {
	ID        int64
	CourseID  int64
	StartsAt  time.Time
	Holes     sql.NullString
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}
