// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: players.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (name, phone, email, username, password_digest, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
RETURNING id, name, phone, email, username
`

type CreatePlayerParams struct {
	Name           sql.NullString
	Phone          sql.NullString
	Email          sql.NullString
	Username       sql.NullString
	PasswordDigest sql.NullString
}

type CreatePlayerRow struct {
	ID       int64
	Name     sql.NullString
	Phone    sql.NullString
	Email    sql.NullString
	Username sql.NullString
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (CreatePlayerRow, error) {
	row := q.db.QueryRowContext(ctx, createPlayer,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Username,
		arg.PasswordDigest,
	)
	var i CreatePlayerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Username,
	)
	return i, err
}

const getPlayerByEmail = `-- name: GetPlayerByEmail :one
SELECT id, name, phone, email, username, password_digest
FROM players
WHERE email = $1
`

type GetPlayerByEmailRow struct {
	ID             int64
	Name           sql.NullString
	Phone          sql.NullString
	Email          sql.NullString
	Username       sql.NullString
	PasswordDigest sql.NullString
}

func (q *Queries) GetPlayerByEmail(ctx context.Context, email sql.NullString) (GetPlayerByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByEmail, email)
	var i GetPlayerByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Username,
		&i.PasswordDigest,
	)
	return i, err
}

const getPlayerByID = `-- name: GetPlayerByID :one
SELECT id, name, phone, email, username
FROM players
WHERE id = $1
`

type GetPlayerByIDRow struct {
	ID       int64
	Name     sql.NullString
	Phone    sql.NullString
	Email    sql.NullString
	Username sql.NullString
}

func (q *Queries) GetPlayerByID(ctx context.Context, id int64) (GetPlayerByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByID, id)
	var i GetPlayerByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Username,
	)
	return i, err
}

const getPlayerByUsername = `-- name: GetPlayerByUsername :one
SELECT id, name, phone, email, username, password_digest
FROM players
WHERE username = $1
`

type GetPlayerByUsernameRow struct {
	ID             int64
	Name           sql.NullString
	Phone          sql.NullString
	Email          sql.NullString
	Username       sql.NullString
	PasswordDigest sql.NullString
}

func (q *Queries) GetPlayerByUsername(ctx context.Context, username sql.NullString) (GetPlayerByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByUsername, username)
	var i GetPlayerByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Username,
		&i.PasswordDigest,
	)
	return i, err
}

const getPlayerPasswordByID = `-- name: GetPlayerPasswordByID :one
SELECT password_digest
FROM players
WHERE id = $1
`

func (q *Queries) GetPlayerPasswordByID(ctx context.Context, id int64) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getPlayerPasswordByID, id)
	var password_digest sql.NullString
	err := row.Scan(&password_digest)
	return password_digest, err
}

const listPlayers = `-- name: ListPlayers :many
SELECT id, name, phone, email, username
FROM players
ORDER BY id
`

type ListPlayersRow struct {
	ID       int64
	Name     sql.NullString
	Phone    sql.NullString
	Email    sql.NullString
	Username sql.NullString
}

func (q *Queries) ListPlayers(ctx context.Context) ([]ListPlayersRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayersRow
	for rows.Next() {
		var i ListPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayer = `-- name: UpdatePlayer :one
UPDATE players
SET name = $2, phone = $3, email = $4, username = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, name, phone, email, username
`

type UpdatePlayerParams struct {
	ID       int64
	Name     sql.NullString
	Phone    sql.NullString
	Email    sql.NullString
	Username sql.NullString
}

type UpdatePlayerRow struct {
	ID       int64
	Name     sql.NullString
	Phone    sql.NullString
	Email    sql.NullString
	Username sql.NullString
}

func (q *Queries) UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) (UpdatePlayerRow, error) {
	row := q.db.QueryRowContext(ctx, updatePlayer,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Username,
	)
	var i UpdatePlayerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Username,
	)
	return i, err
}

const updatePlayerPassword = `-- name: UpdatePlayerPassword :exec
UPDATE players
SET password_digest = $2, updated_at = NOW()
WHERE id = $1
`

type UpdatePlayerPasswordParams struct {
	ID             int64
	PasswordDigest sql.NullString
}

func (q *Queries) UpdatePlayerPassword(ctx context.Context, arg UpdatePlayerPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayerPassword, arg.ID, arg.PasswordDigest)
	return err
}
