// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservations.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getActiveReservationByTeeTimeID = `-- name: GetActiveReservationByTeeTimeID :one
SELECT id, tee_time_id, booked_by_player_id, status, party_size, provider,
       external_reservation_id, hold_expires_at, failure_reason, created_at, updated_at
FROM reservations
WHERE tee_time_id = $1
  AND status IN ('pending', 'held', 'confirmed')
`

func (q *Queries) GetActiveReservationByTeeTimeID(ctx context.Context, teeTimeID int64) (Reservation, error) {
	row := q.db.QueryRowContext(ctx, getActiveReservationByTeeTimeID, teeTimeID)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.TeeTimeID,
		&i.BookedByPlayerID,
		&i.Status,
		&i.PartySize,
		&i.Provider,
		&i.ExternalReservationID,
		&i.HoldExpiresAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReservationByID = `-- name: GetReservationByID :one
SELECT id, tee_time_id, booked_by_player_id, status, party_size, provider,
       external_reservation_id, hold_expires_at, failure_reason, created_at, updated_at
FROM reservations
WHERE id = $1
`

func (q *Queries) GetReservationByID(ctx context.Context, id int64) (Reservation, error) {
	row := q.db.QueryRowContext(ctx, getReservationByID, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.TeeTimeID,
		&i.BookedByPlayerID,
		&i.Status,
		&i.PartySize,
		&i.Provider,
		&i.ExternalReservationID,
		&i.HoldExpiresAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertReservation = `-- name: InsertReservation :one
INSERT INTO reservations (
    tee_time_id, booked_by_player_id, status, party_size, provider,
    external_reservation_id, hold_expires_at, failure_reason, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW())
RETURNING id, tee_time_id, booked_by_player_id, status, party_size, provider,
          external_reservation_id, hold_expires_at, failure_reason, created_at, updated_at
`

type InsertReservationParams struct {
	TeeTimeID             int64
	BookedByPlayerID      int64
	Status                string
	PartySize             int32
	Provider              string
	ExternalReservationID sql.NullString
	HoldExpiresAt         sql.NullTime
	FailureReason         sql.NullString
}

func (q *Queries) InsertReservation(ctx context.Context, arg InsertReservationParams) (Reservation, error) {
	row := q.db.QueryRowContext(ctx, insertReservation,
		arg.TeeTimeID,
		arg.BookedByPlayerID,
		arg.Status,
		arg.PartySize,
		arg.Provider,
		arg.ExternalReservationID,
		arg.HoldExpiresAt,
		arg.FailureReason,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.TeeTimeID,
		&i.BookedByPlayerID,
		&i.Status,
		&i.PartySize,
		&i.Provider,
		&i.ExternalReservationID,
		&i.HoldExpiresAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertReservationPlayer = `-- name: InsertReservationPlayer :one
INSERT INTO reservation_players (reservation_id, player_id, guest_name, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
RETURNING id, reservation_id, player_id, guest_name, created_at, updated_at
`

type InsertReservationPlayerParams struct {
	ReservationID int64
	PlayerID      sql.NullInt64
	GuestName     sql.NullString
}

func (q *Queries) InsertReservationPlayer(ctx context.Context, arg InsertReservationPlayerParams) (ReservationPlayer, error) {
	row := q.db.QueryRowContext(ctx, insertReservationPlayer, arg.ReservationID, arg.PlayerID, arg.GuestName)
	var i ReservationPlayer
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.PlayerID,
		&i.GuestName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReservationPlayers = `-- name: ListReservationPlayers :many
SELECT id, reservation_id, player_id, guest_name, created_at, updated_at
FROM reservation_players
WHERE reservation_id = $1
ORDER BY id
`

func (q *Queries) ListReservationPlayers(ctx context.Context, reservationID int64) ([]ReservationPlayer, error) {
	rows, err := q.db.QueryContext(ctx, listReservationPlayers, reservationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReservationPlayer
	for rows.Next() {
		var i ReservationPlayer
		if err := rows.Scan(
			&i.ID,
			&i.ReservationID,
			&i.PlayerID,
			&i.GuestName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReservation = `-- name: UpdateReservation :one
UPDATE reservations
SET status = $2,
    external_reservation_id = $3,
    hold_expires_at = $4,
    failure_reason = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, tee_time_id, booked_by_player_id, status, party_size, provider,
          external_reservation_id, hold_expires_at, failure_reason, created_at, updated_at
`

type UpdateReservationParams struct {
	ID                    int64
	Status                string
	ExternalReservationID sql.NullString
	HoldExpiresAt         sql.NullTime
	FailureReason         sql.NullString
}

func (q *Queries) UpdateReservation(ctx context.Context, arg UpdateReservationParams) (Reservation, error) {
	row := q.db.QueryRowContext(ctx, updateReservation,
		arg.ID,
		arg.Status,
		arg.ExternalReservationID,
		arg.HoldExpiresAt,
		arg.FailureReason,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.TeeTimeID,
		&i.BookedByPlayerID,
		&i.Status,
		&i.PartySize,
		&i.Provider,
		&i.ExternalReservationID,
		&i.HoldExpiresAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
