// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tee_times.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const getTeeTimeByID = `-- name: GetTeeTimeByID :one
SELECT id, course_id, starts_at, holes, status, capacity, available_slots, price_cents, currency,
       created_at, updated_at
FROM tee_times
WHERE id = $1
`

type GetTeeTimeByIDRow struct {
	ID             int64
	CourseID       int64
	StartsAt       time.Time
	Holes          sql.NullString
	Status         string
	Capacity       sql.NullInt32
	AvailableSlots sql.NullInt32
	PriceCents     sql.NullInt32
	Currency       sql.NullString
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetTeeTimeByID(ctx context.Context, id int64) (GetTeeTimeByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTeeTimeByID, id)
	var i GetTeeTimeByIDRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.StartsAt,
		&i.Holes,
		&i.Status,
		&i.Capacity,
		&i.AvailableSlots,
		&i.PriceCents,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeeTimeByProviderExternalID = `-- name: GetTeeTimeByProviderExternalID :one
SELECT t.id, t.course_id, t.starts_at, t.holes, t.status, t.capacity, t.available_slots,
       t.price_cents, t.currency, t.created_at, t.updated_at
FROM tee_time_providers tp
JOIN tee_times t ON t.id = tp.tee_time_id
WHERE tp.provider = $1 AND tp.external_id = $2
`

type GetTeeTimeByProviderExternalIDParams struct {
	Provider   string
	ExternalID string
}

type GetTeeTimeByProviderExternalIDRow struct {
	ID             int64
	CourseID       int64
	StartsAt       time.Time
	Holes          sql.NullString
	Status         string
	Capacity       sql.NullInt32
	AvailableSlots sql.NullInt32
	PriceCents     sql.NullInt32
	Currency       sql.NullString
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetTeeTimeByProviderExternalID(ctx context.Context, arg GetTeeTimeByProviderExternalIDParams) (GetTeeTimeByProviderExternalIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTeeTimeByProviderExternalID, arg.Provider, arg.ExternalID)
	var i GetTeeTimeByProviderExternalIDRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.StartsAt,
		&i.Holes,
		&i.Status,
		&i.Capacity,
		&i.AvailableSlots,
		&i.PriceCents,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeeTimeProvider = `-- name: GetTeeTimeProvider :one
SELECT id, tee_time_id, provider, external_id
FROM tee_time_providers
WHERE provider = $1 AND external_id = $2
`

type GetTeeTimeProviderParams struct {
	Provider   string
	ExternalID string
}

type GetTeeTimeProviderRow struct {
	ID         int64
	TeeTimeID  int64
	Provider   string
	ExternalID string
}

func (q *Queries) GetTeeTimeProvider(ctx context.Context, arg GetTeeTimeProviderParams) (GetTeeTimeProviderRow, error) {
	row := q.db.QueryRowContext(ctx, getTeeTimeProvider, arg.Provider, arg.ExternalID)
	var i GetTeeTimeProviderRow
	err := row.Scan(
		&i.ID,
		&i.TeeTimeID,
		&i.Provider,
		&i.ExternalID,
	)
	return i, err
}

const insertTeeTime = `-- name: InsertTeeTime :one
INSERT INTO tee_times (
    course_id, starts_at, holes, status, capacity, available_slots, price_cents, currency,
    created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW())
RETURNING id, course_id, starts_at, holes, status, capacity, available_slots, price_cents, currency,
          created_at, updated_at
`

type InsertTeeTimeParams struct {
	CourseID       int64
	StartsAt       time.Time
	Holes          sql.NullString
	Status         string
	Capacity       sql.NullInt32
	AvailableSlots sql.NullInt32
	PriceCents     sql.NullInt32
	Currency       sql.NullString
}

type InsertTeeTimeRow struct {
	ID             int64
	CourseID       int64
	StartsAt       time.Time
	Holes          sql.NullString
	Status         string
	Capacity       sql.NullInt32
	AvailableSlots sql.NullInt32
	PriceCents     sql.NullInt32
	Currency       sql.NullString
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) InsertTeeTime(ctx context.Context, arg InsertTeeTimeParams) (InsertTeeTimeRow, error) {
	row := q.db.QueryRowContext(ctx, insertTeeTime,
		arg.CourseID,
		arg.StartsAt,
		arg.Holes,
		arg.Status,
		arg.Capacity,
		arg.AvailableSlots,
		arg.PriceCents,
		arg.Currency,
	)
	var i InsertTeeTimeRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.StartsAt,
		&i.Holes,
		&i.Status,
		&i.Capacity,
		&i.AvailableSlots,
		&i.PriceCents,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTeeTimeProvider = `-- name: InsertTeeTimeProvider :one
INSERT INTO tee_time_providers (tee_time_id, provider, external_id, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
RETURNING id, tee_time_id, provider, external_id
`

type InsertTeeTimeProviderParams struct {
	TeeTimeID  int64
	Provider   string
	ExternalID string
}

type InsertTeeTimeProviderRow struct {
	ID         int64
	TeeTimeID  int64
	Provider   string
	ExternalID string
}

func (q *Queries) InsertTeeTimeProvider(ctx context.Context, arg InsertTeeTimeProviderParams) (InsertTeeTimeProviderRow, error) {
	row := q.db.QueryRowContext(ctx, insertTeeTimeProvider, arg.TeeTimeID, arg.Provider, arg.ExternalID)
	var i InsertTeeTimeProviderRow
	err := row.Scan(
		&i.ID,
		&i.TeeTimeID,
		&i.Provider,
		&i.ExternalID,
	)
	return i, err
}

const listTeeTimesByCourseAndWindow = `-- name: ListTeeTimesByCourseAndWindow :many
SELECT id, course_id, starts_at, holes, status, capacity, available_slots, price_cents, currency,
       created_at, updated_at
FROM tee_times
WHERE course_id = $1
  AND starts_at >= $2
  AND starts_at < $3
ORDER BY starts_at, id
`

type ListTeeTimesByCourseAndWindowParams struct {
	CourseID   int64
	StartsAt   time.Time
	StartsAt_2 time.Time
}

type ListTeeTimesByCourseAndWindowRow struct {
	ID             int64
	CourseID       int64
	StartsAt       time.Time
	Holes          sql.NullString
	Status         string
	Capacity       sql.NullInt32
	AvailableSlots sql.NullInt32
	PriceCents     sql.NullInt32
	Currency       sql.NullString
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) ListTeeTimesByCourseAndWindow(ctx context.Context, arg ListTeeTimesByCourseAndWindowParams) ([]ListTeeTimesByCourseAndWindowRow, error) {
	rows, err := q.db.QueryContext(ctx, listTeeTimesByCourseAndWindow, arg.CourseID, arg.StartsAt, arg.StartsAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeeTimesByCourseAndWindowRow
	for rows.Next() {
		var i ListTeeTimesByCourseAndWindowRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.StartsAt,
			&i.Holes,
			&i.Status,
			&i.Capacity,
			&i.AvailableSlots,
			&i.PriceCents,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeeTimeCache = `-- name: UpdateTeeTimeCache :one
UPDATE tee_times
SET holes = $2,
    status = $3,
    capacity = $4,
    available_slots = $5,
    price_cents = $6,
    currency = $7,
    starts_at = $8,
    updated_at = NOW()
WHERE id = $1
RETURNING id, course_id, starts_at, holes, status, capacity, available_slots, price_cents, currency,
          created_at, updated_at
`

type UpdateTeeTimeCacheParams struct {
	ID             int64
	Holes          sql.NullString
	Status         string
	Capacity       sql.NullInt32
	AvailableSlots sql.NullInt32
	PriceCents     sql.NullInt32
	Currency       sql.NullString
	StartsAt       time.Time
}

type UpdateTeeTimeCacheRow struct {
	ID             int64
	CourseID       int64
	StartsAt       time.Time
	Holes          sql.NullString
	Status         string
	Capacity       sql.NullInt32
	AvailableSlots sql.NullInt32
	PriceCents     sql.NullInt32
	Currency       sql.NullString
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) UpdateTeeTimeCache(ctx context.Context, arg UpdateTeeTimeCacheParams) (UpdateTeeTimeCacheRow, error) {
	row := q.db.QueryRowContext(ctx, updateTeeTimeCache,
		arg.ID,
		arg.Holes,
		arg.Status,
		arg.Capacity,
		arg.AvailableSlots,
		arg.PriceCents,
		arg.Currency,
		arg.StartsAt,
	)
	var i UpdateTeeTimeCacheRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.StartsAt,
		&i.Holes,
		&i.Status,
		&i.Capacity,
		&i.AvailableSlots,
		&i.PriceCents,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTeeTimeStatus = `-- name: UpdateTeeTimeStatus :one
UPDATE tee_times
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, course_id, starts_at, holes, status, capacity, available_slots, price_cents, currency,
          created_at, updated_at
`

type UpdateTeeTimeStatusParams struct {
	ID     int64
	Status string
}

type UpdateTeeTimeStatusRow struct {
	ID             int64
	CourseID       int64
	StartsAt       time.Time
	Holes          sql.NullString
	Status         string
	Capacity       sql.NullInt32
	AvailableSlots sql.NullInt32
	PriceCents     sql.NullInt32
	Currency       sql.NullString
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) UpdateTeeTimeStatus(ctx context.Context, arg UpdateTeeTimeStatusParams) (UpdateTeeTimeStatusRow, error) {
	row := q.db.QueryRowContext(ctx, updateTeeTimeStatus, arg.ID, arg.Status)
	var i UpdateTeeTimeStatusRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.StartsAt,
		&i.Holes,
		&i.Status,
		&i.Capacity,
		&i.AvailableSlots,
		&i.PriceCents,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
